export interface DestinationCost {
  hotel: number;
  food: number;
  transport: number;
  attractions: number;
  activities: number;
  shopping: number;
  dailyAverage: number;
  category: "Budget" | "Mid-Range" | "Luxury";
}

export interface Destination {
  id: string;
  name: string;
  country: string;
  region: string;
  image: string; // Real-world image, no emojis
  gallery: string[];
  popularityScore: number; // 1-5
  
  // Overview
  overview: string;
  countryInfo: string;
  historicalSignificance: string;
  weatherInsights: string;
  bestTimeToVisit: string;
  safetyTips: string;
  transportationDetails: string;

  // Features
  mustVisitPlaces: string[];
  topExperiences: string[];
  famousFor: string[];
  hiddenGems: string[];
  bestPhotoSpots: string[];
  localFoodSpecialties: string[];
  nightlife: string[];
  adventureActivities: string[];
  familyFriendly: string[];

  // Tags/Filters
  tags: string[];
  category: "Beaches" | "Mountains" | "Historical" | "Budget" | "Luxury" | "Hidden Gems";
  budgetCategory: "Budget" | "Mid-Range" | "Luxury";
  adventureLevel: "Low" | "Medium" | "High";

  // Detailed Cost
  estimatedCosts: DestinationCost;
}

export const DESTINATIONS: Destination[] = [
  {
    id: "dest-1",
    name: "Jaipur",
    country: "India",
    region: "South Asia",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.6,
    overview: "Known as the Pink City, Jaipur is a vibrant tapestry of majestic forts, royal palaces, and bustling bazaars that encapsulate the historic essence of Rajasthan.",
    countryInfo: "India is a vast South Asian country with diverse terrain, deeply historic sites, and vibrant cultural traditions.",
    historicalSignificance: "Founded in 1727 by Jai Singh II, it was one of the earliest planned cities of modern India and served as the capital of the Kachwaha Rajput rulers.",
    weatherInsights: "Hot, semi-arid climate. Summers are extremely hot, while winters are mild and pleasant.",
    bestTimeToVisit: "October to March, when the weather is cool and dry.",
    safetyTips: "Generally safe for tourists. Beware of pickpockets in crowded bazaars and negotiate auto-rickshaw fares in advance.",
    transportationDetails: "Well connected by Jaipur International Airport, extensive rail networks, and modern metro. Auto-rickshaws and app-based cabs are best for local transit.",
    
    mustVisitPlaces: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar", "Nahargarh Fort"],
    topExperiences: ["Elephant ride at Amber Fort", "Shopping in Johari Bazaar", "Hot air balloon ride", "Rajasthani thali dinner at Chokhi Dhani"],
    famousFor: ["Pink architecture", "Block printing", "Kundan jewelry", "Rajput history"],
    hiddenGems: ["Panna Meena Ka Kund", "Gatore Ki Chhatriyan", "Patrika Gate"],
    bestPhotoSpots: ["Hawa Mahal facade at sunrise", "Amber Fort courtyard", "Patrika Gate arches"],
    localFoodSpecialties: ["Dal Bati Churma", "Pyaz Ki Kachori", "Ghevar", "Laal Maas"],
    nightlife: ["Bar Palladio", "Nahargarh Fort sunset views", "Rambagh Palace lounges"],
    adventureActivities: ["Hot air ballooning", "Jhalana leopard safari", "Cycling tours"],
    familyFriendly: ["City Palace museum", "Albert Hall Museum", "Puppet shows"],

    tags: ["Heritage", "Culture", "Architecture", "Shopping"],
    category: "Historical",
    budgetCategory: "Mid-Range",
    adventureLevel: "Medium",

    estimatedCosts: {
      hotel: 60,
      food: 20,
      transport: 10,
      attractions: 15,
      activities: 30,
      shopping: 40,
      dailyAverage: 105,
      category: "Mid-Range"
    }
  },
  {
    id: "dest-2",
    name: "Bali",
    country: "Indonesia",
    region: "Southeast Asia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.9,
    overview: "The Island of the Gods offers lush rice terraces, ancient temples, vibrant nightlife, and a deeply spiritual culture set against stunning beaches.",
    countryInfo: "Indonesia is a massive archipelago nation known for its thousands of volcanic islands, diverse ethnic groups, and beaches.",
    historicalSignificance: "Bali is the only Hindu-majority province in Indonesia, preserving ancient Majapahit culture and thousands of intricate temples.",
    weatherInsights: "Tropical, warm, and humid year-round with a distinct wet and dry season.",
    bestTimeToVisit: "May to September during the dry season.",
    safetyTips: "Watch out for strong ocean currents, wear helmets when riding scooters, and be respectful of local religious ceremonies.",
    transportationDetails: "Scooter rentals and ride-hailing apps (Gojek/Grab) are the most popular ways to get around. Public transport is very limited.",
    
    mustVisitPlaces: ["Uluwatu Temple", "Tegallalang Rice Terrace", "Sacred Monkey Forest Sanctuary", "Mount Batur", "Nusa Penida"],
    topExperiences: ["Surfing in Canggu", "Sunrise hike at Mount Batur", "Traditional Balinese massage", "Kecak Fire Dance"],
    famousFor: ["Beaches", "Hindu Temples", "Yoga & Wellness", "Digital Nomad Hubs"],
    hiddenGems: ["Sekumpul Waterfall", "Amed coastal village", "Sidemen valley"],
    bestPhotoSpots: ["Lempuyang Temple (Gates of Heaven)", "Tegallalang swings", "Diamond Beach"],
    localFoodSpecialties: ["Nasi Goreng", "Babi Guling", "Sate Lilit", "Smoothie Bowls"],
    nightlife: ["Finns Beach Club", "Potato Head", "La Favela", "Ulu Cliffhouse"],
    adventureActivities: ["Scuba diving", "White water rafting", "Volcano trekking"],
    familyFriendly: ["Waterbom Bali", "Bali Safari", "Turtle Conservation Center"],

    tags: ["Beach", "Nature", "Wellness", "Surfing", "Spiritual"],
    category: "Beaches",
    budgetCategory: "Budget",
    adventureLevel: "High",

    estimatedCosts: {
      hotel: 45,
      food: 25,
      transport: 8,
      attractions: 10,
      activities: 35,
      shopping: 15,
      dailyAverage: 90,
      category: "Budget"
    }
  },
  {
    id: "dest-3",
    name: "Paris",
    country: "France",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1173&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    gallery: [],
    popularityScore: 5.0,
    overview: "The City of Light is a global center for art, fashion, gastronomy, and culture, featuring iconic landmarks and charming 19th-century streetscapes.",
    countryInfo: "France, in Western Europe, encompasses medieval cities, alpine villages, and Mediterranean beaches.",
    historicalSignificance: "A major city since Roman times, Paris played a central role in the Renaissance, the Age of Enlightenment, and the French Revolution.",
    weatherInsights: "Temperate climate. Summers are warm and pleasant, while winters are cold and damp.",
    bestTimeToVisit: "April to June and September to October for the best weather and smaller crowds.",
    safetyTips: "Beware of pickpockets around major tourist sites and on the Metro. Watch out for street scams.",
    transportationDetails: "Excellent public transit including the extensive Metro network, RER trains, and buses. Highly walkable city center.",
    
    mustVisitPlaces: ["Eiffel Tower", "Louvre Museum", "Notre-Dame Cathedral", "Palace of Versailles", "Montmartre"],
    topExperiences: ["Seine river cruise", "Macaron tasting", "Cabaret show at Moulin Rouge", "Sunset at Sacré-Cœur"],
    famousFor: ["Art Museums", "Fashion", "Café Culture", "Romance"],
    hiddenGems: ["Musée de l'Orangerie", "Promenade Plantée", "Sainte-Chapelle", "Catacombs"],
    bestPhotoSpots: ["Trocadéro at sunrise", "Rue de l'Université", "Pont Alexandre III"],
    localFoodSpecialties: ["Croissants", "Escargot", "French Onion Soup", "Steak Frites", "Crêpes"],
    nightlife: ["Le Marais bars", "Pigalle clubs", "Rooftop bars overlooking the Eiffel Tower"],
    adventureActivities: ["None specifically", "Extensive walking tours", "Biking along the Seine"],
    familyFriendly: ["Disneyland Paris", "Cité des Sciences", "Jardin du Luxembourg"],

    tags: ["Romance", "Art", "Food", "History", "Luxury"],
    category: "Luxury",
    budgetCategory: "Luxury",
    adventureLevel: "Low",

    estimatedCosts: {
      hotel: 250,
      food: 80,
      transport: 20,
      attractions: 45,
      activities: 60,
      shopping: 100,
      dailyAverage: 350,
      category: "Luxury"
    }
  },
  {
    id: "dest-4",
    name: "Queenstown",
    country: "New Zealand",
    region: "Oceania",
    image: "https://images.unsplash.com/photo-1593755673003-8ca8dbf906c2?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    gallery: [],
    popularityScore: 4.5,
    overview: "The 'Adventure Capital of the World' sits on the shores of the South Island’s Lake Wakatipu, set against the dramatic Southern Alps.",
    countryInfo: "New Zealand is renowned for its spectacular natural landscapes, Maori culture, and outdoor adventure.",
    historicalSignificance: "Originally a gold mining town in the 1860s, it transformed into a world-class resort destination over the 20th century.",
    weatherInsights: "Alpine climate with four distinct seasons. Snowy winters and warm, dry summers.",
    bestTimeToVisit: "December to February for summer hiking, June to August for winter sports.",
    safetyTips: "Very safe, but always check weather conditions before heading into alpine environments.",
    transportationDetails: "Compact and walkable downtown. Buses connect major areas, but renting a car is best for exploring the surrounding region.",
    
    mustVisitPlaces: ["Milford Sound", "Lake Wakatipu", "Bob's Peak", "Coronet Peak", "Arrowtown"],
    topExperiences: ["Bungy jumping at Kawarau Bridge", "Shotover Jet boat ride", "Skyline Gondola & Luge", "Wine tasting in Central Otago"],
    famousFor: ["Extreme Sports", "Stunning Scenery", "Pinot Noir", "Lord of the Rings filming locations"],
    hiddenGems: ["Moke Lake", "Glenorchy", "Onsen Hot Pools"],
    bestPhotoSpots: ["View from Bob's Peak", "Glenorchy Wharf", "Bennett's Bluff viewpoint"],
    localFoodSpecialties: ["Fergburger", "Southland Cheese Roll", "Green-lipped mussels", "Hokey Pokey ice cream"],
    nightlife: ["Ice Bar", "Searle Lane", "Cowboys Queenstown"],
    adventureActivities: ["Bungy jumping", "Skydiving", "Heli-skiing", "Canyon swing"],
    familyFriendly: ["Kiwi Birdlife Park", "TSS Earnslaw cruise", "Luge track"],

    tags: ["Adventure", "Nature", "Mountains", "Winter Sports"],
    category: "Mountains",
    budgetCategory: "Luxury",
    adventureLevel: "High",

    estimatedCosts: {
      hotel: 180,
      food: 60,
      transport: 30,
      attractions: 20,
      activities: 150,
      shopping: 40,
      dailyAverage: 280,
      category: "Luxury"
    }
  }  ,{
    id: "dest-5",
    name: "Lisbon",
    country: "Portugal",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1697748525265-7431cba075b6?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    gallery: [],
    popularityScore: 4.5,
    overview: "Hilly streets, azulejo tiles and Atlantic soul.",
    countryInfo: "Portugal offers rich maritime history, stunning coastlines, and incredible gastronomy.",
    historicalSignificance: "One of the oldest cities in the world, and the oldest in Western Europe.",
    weatherInsights: "Mediterranean climate with mild winters and warm summers.",
    bestTimeToVisit: "March to May or September to October.",
    safetyTips: "Watch out for pickpockets on crowded trams like Tram 28.",
    transportationDetails: "Walkable but hilly; utilizes a network of vintage trams, funiculars, and metro.",
    mustVisitPlaces: ["Belém Tower", "Jerónimos Monastery", "Alfama District"],
    topExperiences: ["Tram 28 Ride", "Listening to Fado music", "Eating Pastéis de Nata"],
    famousFor: ["Azulejo tiles", "Fado music", "Seafood"],
    hiddenGems: ["LX Factory", "Miradouro da Senhora do Monte"],
    bestPhotoSpots: ["Praça do Comércio", "Miradouro de Santa Luzia"],
    localFoodSpecialties: ["Pastéis de Nata", "Bacalhau à Brás"],
    nightlife: ["Bairro Alto", "Pink Street"],
    adventureActivities: ["Surfing at Cascais"],
    familyFriendly: ["Oceanário de Lisboa"],
    tags: ["Culture", "Food", "History"],
    category: "Historical",
    budgetCategory: "Mid-Range",
    adventureLevel: "Low",
    estimatedCosts: { hotel: 120, food: 40, transport: 10, attractions: 20, activities: 30, shopping: 20, dailyAverage: 240, category: "Mid-Range" }
  },
  {
    id: "dest-6",
    name: "Bangkok",
    country: "Thailand",
    region: "Southeast Asia",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?q=80&w=1050&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    gallery: [],
    popularityScore: 4.8,
    overview: "Temples, street food and neon-lit nights.",
    countryInfo: "Thailand is known for tropical beaches, opulent royal palaces, and ornate temples.",
    historicalSignificance: "Capital of Thailand since 1782, deeply rooted in Buddhist traditions.",
    weatherInsights: "Tropical monsoon climate, hot and humid year-round.",
    bestTimeToVisit: "November to February when it's cooler and drier.",
    safetyTips: "Be cautious of gem scams and overly friendly tuk-tuk drivers.",
    transportationDetails: "BTS Skytrain and MRT are best. Tuk-tuks for short trips.",
    mustVisitPlaces: ["Grand Palace", "Wat Arun", "Chatuchak Market"],
    topExperiences: ["Floating Market Boat Tour", "Street food at Chinatown"],
    famousFor: ["Street food", "Nightlife", "Temples"],
    hiddenGems: ["Talad Noi", "Bang Krachao"],
    bestPhotoSpots: ["Wat Arun at sunset", "Mahanakhon SkyWalk"],
    localFoodSpecialties: ["Pad Thai", "Tom Yum Goong", "Mango Sticky Rice"],
    nightlife: ["Khao San Road", "Sukhumvit Soi 11", "Rooftop Bars"],
    adventureActivities: ["Muay Thai class"],
    familyFriendly: ["Sea Life Bangkok", "Lumpini Park"],
    tags: ["Food", "Culture", "Nightlife"],
    category: "Budget",
    budgetCategory: "Budget",
    adventureLevel: "Medium",
    estimatedCosts: { hotel: 50, food: 20, transport: 5, attractions: 15, activities: 25, shopping: 30, dailyAverage: 145, category: "Budget" }
  },
  {
    id: "dest-7",
    name: "Istanbul",
    country: "Turkey",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1626956291772-3aa243614fd0?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    gallery: [],
    popularityScore: 4.7,
    overview: "Where East meets West — a city of mosques and bazaars.",
    countryInfo: "Straddling Europe and Asia across the Bosphorus Strait.",
    historicalSignificance: "Former capital of the Roman, Byzantine, and Ottoman empires.",
    weatherInsights: "Mediterranean climate with hot summers and cool winters.",
    bestTimeToVisit: "April to May and September to October.",
    safetyTips: "Generally safe; keep valuables secure in busy bazaars.",
    transportationDetails: "Extensive tram, metro, and ferry network.",
    mustVisitPlaces: ["Hagia Sophia", "Blue Mosque", "Grand Bazaar"],
    topExperiences: ["Bosphorus Sunset Cruise", "Turkish Bath (Hammam)"],
    famousFor: ["Two continents", "Ottoman Architecture", "Turkish Delight"],
    hiddenGems: ["Balat District", "Chora Church"],
    bestPhotoSpots: ["Galata Tower", "Ortaköy Mosque"],
    localFoodSpecialties: ["Doner Kebab", "Baklava", "Turkish Tea"],
    nightlife: ["Kadıköy bars", "Istiklal Street"],
    adventureActivities: ["None"],
    familyFriendly: ["Miniaturk", "Basilica Cistern"],
    tags: ["History", "Culture", "Food"],
    category: "Historical",
    budgetCategory: "Mid-Range",
    adventureLevel: "Low",
    estimatedCosts: { hotel: 90, food: 30, transport: 5, attractions: 20, activities: 25, shopping: 40, dailyAverage: 210, category: "Mid-Range" }
  },
  {
    id: "dest-8",
    name: "Barcelona",
    country: "Spain",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    gallery: [],
    popularityScore: 4.8,
    overview: "Gaudí's playground — architecture, tapas and beaches.",
    countryInfo: "Spain is a diverse country with Mediterranean beaches and vibrant culture.",
    historicalSignificance: "Capital of Catalonia with a rich history dating back to Roman times.",
    weatherInsights: "Mediterranean climate; hot summers and mild winters.",
    bestTimeToVisit: "May to June and September to October.",
    safetyTips: "High risk of pickpocketing, especially on Las Ramblas and the Metro.",
    transportationDetails: "Excellent metro and bus system. Very walkable city center.",
    mustVisitPlaces: ["Sagrada Familia", "Park Güell", "Gothic Quarter"],
    topExperiences: ["Sagrada Familia Tour", "Tapas Bar Hopping"],
    famousFor: ["Antoni Gaudí", "FC Barcelona", "Beaches"],
    hiddenGems: ["Bunkers del Carmel", "Hospital de Sant Pau"],
    bestPhotoSpots: ["Park Güell terrace", "Casa Batlló facade"],
    localFoodSpecialties: ["Paella", "Tapas", "Crema Catalana"],
    nightlife: ["El Born", "Port Olímpic clubs"],
    adventureActivities: ["Parasailing"],
    familyFriendly: ["Magic Fountain", "CosmoCaixa"],
    tags: ["Architecture", "Beach", "Nightlife"],
    category: "Historical",
    budgetCategory: "Mid-Range",
    adventureLevel: "Medium",
    estimatedCosts: { hotel: 150, food: 60, transport: 15, attractions: 30, activities: 40, shopping: 50, dailyAverage: 345, category: "Mid-Range" }
  }  ,{
    id: "dest-9",
    name: "Goa",
    country: "India",
    region: "South Asia",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.7,
    overview: "Sun, sand and Portuguese heritage on India's western coast.",
    countryInfo: "India is a vast South Asian country with diverse terrain.",
    historicalSignificance: "A former Portuguese province, known for its well-preserved 17th-century churches.",
    weatherInsights: "Tropical monsoon climate with hot summers and heavy rainfall from June to September.",
    bestTimeToVisit: "November to February.",
    safetyTips: "Swim only in designated safe zones; be cautious of rip currents.",
    transportationDetails: "Rent a scooter or use local taxis. Buses connect major towns.",
    mustVisitPlaces: ["Baga Beach", "Basilica of Bom Jesus", "Fort Aguada", "Dudhsagar Falls"],
    topExperiences: ["Beach hopping", "Exploring spice plantations", "Sunset cruise on Mandovi River"],
    famousFor: ["Beaches", "Seafood", "Nightlife", "Portuguese Architecture"],
    hiddenGems: ["Divar Island", "Netravali Wildlife Sanctuary"],
    bestPhotoSpots: ["Chapora Fort", "Fontainhas Latin Quarter"],
    localFoodSpecialties: ["Fish Curry Rice", "Vindaloo", "Bebinca"],
    nightlife: ["Tito's Lane", "Anjuna Beach parties", "Curlies"],
    adventureActivities: ["Parasailing", "Scuba Diving", "Jet Skiing"],
    familyFriendly: ["Dolphin watching tours", "Naval Aviation Museum"],
    tags: ["Beach", "Nightlife", "Relaxation"],
    category: "Beaches",
    budgetCategory: "Mid-Range",
    adventureLevel: "Medium",
    estimatedCosts: { hotel: 60, food: 25, transport: 10, attractions: 15, activities: 30, shopping: 20, dailyAverage: 160, category: "Mid-Range" }
  },
  {
    id: "dest-10",
    name: "Varanasi",
    country: "India",
    region: "South Asia",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.4,
    overview: "One of the world's oldest cities on the sacred Ganges.",
    countryInfo: "India is deeply spiritual with ancient rituals and traditions.",
    historicalSignificance: "Considered the spiritual capital of India, continuously inhabited for over 3000 years.",
    weatherInsights: "Extremely hot summers and cool winters. Monsoon from July to September.",
    bestTimeToVisit: "October to March.",
    safetyTips: "Respect local customs, especially at cremation ghats. Beware of aggressive touts.",
    transportationDetails: "Walking is best along the ghats. E-rickshaws and auto-rickshaws elsewhere.",
    mustVisitPlaces: ["Dashashwamedh Ghat", "Kashi Vishwanath Temple", "Sarnath"],
    topExperiences: ["Ganges Aarti Ceremony", "Sunrise boat ride on the Ganges"],
    famousFor: ["Spirituality", "Ghats", "Silk weaving"],
    hiddenGems: ["Weaver's village", "Alamgir Mosque"],
    bestPhotoSpots: ["Assi Ghat at dawn", "Narrow alleys of the old city"],
    localFoodSpecialties: ["Malaiyo", "Kachori Sabzi", "Banarasi Paan"],
    nightlife: ["Evening Aarti (spiritual rather than party)"],
    adventureActivities: ["None"],
    familyFriendly: ["Boat tours", "Sarnath museum"],
    tags: ["Spiritual", "Culture", "History"],
    category: "Historical",
    budgetCategory: "Budget",
    adventureLevel: "Low",
    estimatedCosts: { hotel: 30, food: 15, transport: 5, attractions: 5, activities: 10, shopping: 20, dailyAverage: 85, category: "Budget" }
  },
  {
    id: "dest-11",
    name: "Rome",
    country: "Italy",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.8,
    overview: "Eternal city of ancient ruins, piazzas and pasta.",
    countryInfo: "Italy is home to incredible history, art, and the Mediterranean coastline.",
    historicalSignificance: "Capital of the Roman Empire and the center of the Catholic Church.",
    weatherInsights: "Mediterranean climate. Hot, dry summers and mild, rainy winters.",
    bestTimeToVisit: "April to June and late September to October.",
    safetyTips: "Beware of pickpockets at major tourist sites and on public transport.",
    transportationDetails: "Metro, buses, and trams. The historic center is highly walkable.",
    mustVisitPlaces: ["Colosseum", "Vatican City", "Pantheon", "Trevi Fountain"],
    topExperiences: ["Touring the Colosseum & Forum", "Tasting authentic gelato"],
    famousFor: ["Roman Ruins", "Vatican", "Pasta and Pizza"],
    hiddenGems: ["Appian Way", "Baths of Caracalla", "Aventine Keyhole"],
    bestPhotoSpots: ["Pincian Hill", "Inside the Pantheon", "Spanish Steps"],
    localFoodSpecialties: ["Carbonara", "Cacio e Pepe", "Suppli"],
    nightlife: ["Trastevere bars", "Testaccio clubs"],
    adventureActivities: ["Gladiator school experience"],
    familyFriendly: ["Borghese Gardens", "Pizza making classes"],
    tags: ["History", "Culture", "Food"],
    category: "Historical",
    budgetCategory: "Luxury",
    adventureLevel: "Low",
    estimatedCosts: { hotel: 160, food: 70, transport: 15, attractions: 40, activities: 35, shopping: 60, dailyAverage: 380, category: "Luxury" }
  },
  {
    id: "dest-12",
    name: "Tokyo",
    country: "Japan",
    region: "East Asia",
    image: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.9,
    overview: "Where ultra-modern meets ancient tradition.",
    countryInfo: "Japan consists of thousands of islands blending ancient traditions with cutting-edge technology.",
    historicalSignificance: "Capital of Japan since 1869, transformed from the small fishing village of Edo.",
    weatherInsights: "Humid subtropical climate. Hot, humid summers and cool winters.",
    bestTimeToVisit: "March to May (cherry blossoms) and September to November.",
    safetyTips: "Extremely safe. Always carry some cash as some small vendors don't take cards.",
    transportationDetails: "Incredibly efficient rail and subway network. Suica/Pasmo cards are essential.",
    mustVisitPlaces: ["Shibuya Crossing", "Senso-ji Temple", "Meiji Shrine", "Tokyo Skytree"],
    topExperiences: ["Tokyo Ramen Bar Crawl", "Akihabara electronics shopping", "Tsukiji Outer Market"],
    famousFor: ["Anime/Manga", "Sushi", "Technology", "Neon lights"],
    hiddenGems: ["Yanaka Ginza", "Omoide Yokocho", "Todoroki Valley"],
    bestPhotoSpots: ["Shibuya Sky", "TeamLab Planets", "Chidorigafuchi (spring)"],
    localFoodSpecialties: ["Sushi", "Ramen", "Tempura", "Yakitori"],
    nightlife: ["Shinjuku Golden Gai", "Roppongi clubs"],
    adventureActivities: ["MariCar (Go-karting)"],
    familyFriendly: ["Tokyo Disneyland", "Ghibli Museum", "Ueno Zoo"],
    tags: ["Technology", "Culture", "Food"],
    category: "Historical",
    budgetCategory: "Luxury",
    adventureLevel: "Medium",
    estimatedCosts: { hotel: 140, food: 60, transport: 20, attractions: 30, activities: 40, shopping: 80, dailyAverage: 370, category: "Luxury" }
  },
  {
    id: "dest-13",
    name: "Dubai",
    country: "UAE",
    region: "Middle East",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.6,
    overview: "Futuristic skyline, luxury malls and desert adventures.",
    countryInfo: "The UAE is known for luxury shopping, ultramodern architecture, and a lively nightlife scene.",
    historicalSignificance: "Grew rapidly from a small fishing village to a global metropolis in a few decades.",
    weatherInsights: "Desert climate. Extremely hot summers and warm, pleasant winters.",
    bestTimeToVisit: "November to March.",
    safetyTips: "Very safe. Respect local laws and modest dress codes in public areas.",
    transportationDetails: "Modern metro system, abundant taxis, and ride-hailing apps.",
    mustVisitPlaces: ["Burj Khalifa", "The Dubai Mall", "Palm Jumeirah", "Dubai Marina"],
    topExperiences: ["Dubai Desert Safari", "Dhow Cruise", "View from Burj Khalifa"],
    famousFor: ["Tallest building", "Luxury shopping", "Artificial islands"],
    hiddenGems: ["Al Fahidi Historical Neighbourhood", "Dubai Miracle Garden"],
    bestPhotoSpots: ["Dubai Frame", "Burj Al Arab beach", "Museum of the Future"],
    localFoodSpecialties: ["Shawarma", "Al Harees", "Luqaimat"],
    nightlife: ["White Dubai", "Zero Gravity", "Soho Garden"],
    adventureActivities: ["Skydiving over Palm Jumeirah", "Dune Bashing", "Indoor Skiing"],
    familyFriendly: ["Aquaventure Waterpark", "Dubai Aquarium", "Global Village"],
    tags: ["Luxury", "Shopping", "Adventure"],
    category: "Luxury",
    budgetCategory: "Luxury",
    adventureLevel: "High",
    estimatedCosts: { hotel: 200, food: 80, transport: 25, attractions: 60, activities: 100, shopping: 150, dailyAverage: 615, category: "Luxury" }
  },
  {
    id: "dest-14",
    name: "New York",
    country: "USA",
    region: "North America",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.9,
    overview: "The Big Apple — museums, Broadway and iconic skyline.",
    countryInfo: "The USA is a vast country with incredibly diverse cities, landscapes, and cultures.",
    historicalSignificance: "A global hub for finance, arts, and culture since the 19th century.",
    weatherInsights: "Continental climate. Hot, humid summers and cold, snowy winters.",
    bestTimeToVisit: "April to June and September to November.",
    safetyTips: "Generally safe. Stay alert in crowded tourist areas to avoid pickpockets.",
    transportationDetails: "The 24/7 Subway system is the fastest way to get around. Taxis are everywhere.",
    mustVisitPlaces: ["Statue of Liberty", "Central Park", "Times Square", "Metropolitan Museum of Art"],
    topExperiences: ["Broadway Show", "Walking the Brooklyn Bridge", "MoMA Art Museum"],
    famousFor: ["Skyscrapers", "Broadway", "Yellow Cabs", "Pizza"],
    hiddenGems: ["The Cloisters", "High Line Park", "Governors Island"],
    bestPhotoSpots: ["Top of the Rock", "DUMBO Manhattan Bridge view", "Vessel"],
    localFoodSpecialties: ["NY Slice Pizza", "Bagels", "Pastrami Sandwich", "Cheesecake"],
    nightlife: ["Meatpacking District clubs", "Greenwich Village jazz bars", "Rooftop lounges"],
    adventureActivities: ["Helicopter tour over Manhattan"],
    familyFriendly: ["American Museum of Natural History", "Central Park Zoo"],
    tags: ["Culture", "Art", "Food"],
    category: "Luxury",
    budgetCategory: "Luxury",
    adventureLevel: "Low",
    estimatedCosts: { hotel: 250, food: 90, transport: 15, attractions: 50, activities: 80, shopping: 100, dailyAverage: 585, category: "Luxury" }
  },
  {
    id: "dest-15",
    name: "Kyoto",
    country: "Japan",
    region: "East Asia",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.8,
    overview: "Ancient capital of Japan with thousands of shrines.",
    countryInfo: "Japan consists of thousands of islands blending ancient traditions with cutting-edge technology.",
    historicalSignificance: "Served as Japan's capital and the emperor's residence from 794 until 1868.",
    weatherInsights: "Humid subtropical. Hot summers and cold winters.",
    bestTimeToVisit: "March to May and October to November.",
    safetyTips: "Extremely safe. Respect photography rules in geisha districts.",
    transportationDetails: "Extensive bus network and subway lines. Biking is highly recommended.",
    mustVisitPlaces: ["Kinkaku-ji (Golden Pavilion)", "Fushimi Inari Shrine", "Arashiyama Bamboo Grove"],
    topExperiences: ["Traditional Tea Ceremony", "Staying in a Ryokan", "Geisha performance"],
    famousFor: ["Temples", "Geisha", "Matcha", "Gardens"],
    hiddenGems: ["Otagi Nenbutsu-ji", "Philosopher's Path", "Kurama-dera"],
    bestPhotoSpots: ["Fushimi Inari Torii gates", "Kiyomizu-dera balcony", "Yasaka Pagoda"],
    localFoodSpecialties: ["Kaiseki", "Matcha Sweets", "Yudofu", "Shojin Ryori"],
    nightlife: ["Pontocho Alley izakayas", "Gion district evening walks"],
    adventureActivities: ["Hiking Mt. Hiei"],
    familyFriendly: ["Toei Kyoto Studio Park", "Kyoto Railway Museum"],
    tags: ["Heritage", "Spiritual", "Culture"],
    category: "Historical",
    budgetCategory: "Luxury",
    adventureLevel: "Low",
    estimatedCosts: { hotel: 160, food: 60, transport: 15, attractions: 25, activities: 50, shopping: 40, dailyAverage: 350, category: "Luxury" }
  },
  {
    id: "dest-16",
    name: "Cape Town",
    country: "South Africa",
    region: "Africa",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.5,
    overview: "Majestic Table Mountain, vineyards and ocean views.",
    countryInfo: "South Africa is known for its diverse wildlife, stunning landscapes, and rich cultural heritage.",
    historicalSignificance: "The oldest city in South Africa, established by the Dutch East India Company in 1652.",
    weatherInsights: "Mediterranean climate. Warm, dry summers and mild, wet winters.",
    bestTimeToVisit: "November to February for summer weather.",
    safetyTips: "Avoid walking alone at night. Use Uber for transport after dark. Keep valuables hidden.",
    transportationDetails: "Uber is the safest and most convenient way. MyCiTi buses are also available.",
    mustVisitPlaces: ["Table Mountain", "Cape of Good Hope", "Robben Island", "V&A Waterfront"],
    topExperiences: ["Table Mountain Hike", "Wine tasting in Stellenbosch", "Seeing penguins at Boulders Beach"],
    famousFor: ["Table Mountain", "Wine", "Beaches", "Nelson Mandela's prison"],
    hiddenGems: ["Kirstenbosch Botanical Gardens", "Bo-Kaap neighborhood", "Chapman's Peak Drive"],
    bestPhotoSpots: ["Lion's Head at sunset", "Colorful houses of Bo-Kaap", "Camps Bay"],
    localFoodSpecialties: ["Braai (BBQ)", "Bobotie", "Biltong", "Gatsby sandwich"],
    nightlife: ["Long Street bars", "Camps Bay sunset clubs"],
    adventureActivities: ["Shark Cage Diving", "Paragliding off Lion's Head", "Surfing"],
    familyFriendly: ["Two Oceans Aquarium", "Penguin Colony"],
    tags: ["Adventure", "Beach", "Nature"],
    category: "Mountains",
    budgetCategory: "Mid-Range",
    adventureLevel: "High",
    estimatedCosts: { hotel: 100, food: 40, transport: 20, attractions: 30, activities: 80, shopping: 30, dailyAverage: 300, category: "Mid-Range" }
  },
  {
    id: "dest-17",
    name: "Maldives",
    country: "Maldives",
    region: "South Asia",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 5.0,
    overview: "Crystal-clear lagoons and overwater bungalows.",
    countryInfo: "An archipelagic state situated in the Indian Ocean known for luxury island resorts.",
    historicalSignificance: "A historic crossroads for Indian Ocean trade routes.",
    weatherInsights: "Tropical monsoon climate. Hot and humid year-round.",
    bestTimeToVisit: "November to April during the dry season.",
    safetyTips: "Extremely safe on resort islands. Respect local Islamic customs on local islands.",
    transportationDetails: "Seaplanes and speedboats connect the airport to resort islands.",
    mustVisitPlaces: ["Male", "Baa Atoll", "Ari Atoll"],
    topExperiences: ["Snorkelling in Maldives", "Staying in an overwater villa", "Submarine tour"],
    famousFor: ["Luxury resorts", "Coral reefs", "Honeymoons"],
    hiddenGems: ["Local island guesthouses", "Bioluminescent beach at Vaadhoo"],
    bestPhotoSpots: ["Overwater bungalows", "Underwater restaurants", "Sandbanks"],
    localFoodSpecialties: ["Mas Huni", "Garudhiya", "Bis Keemiya"],
    nightlife: ["Resort bars", "Beachfront dining"],
    adventureActivities: ["Scuba Diving", "Manta Ray swimming", "Jet Skiing"],
    familyFriendly: ["Dolphin watching", "Snorkeling"],
    tags: ["Luxury", "Beach", "Relaxation"],
    category: "Beaches",
    budgetCategory: "Luxury",
    adventureLevel: "Low",
    estimatedCosts: { hotel: 400, food: 100, transport: 50, attractions: 0, activities: 100, shopping: 20, dailyAverage: 670, category: "Luxury" }
  },
  {
    id: "dest-18",
    name: "Kolkata",
    country: "India",
    region: "South Asia",
    image: "https://images.unsplash.com/photo-1558431382-27e303142255?q=80&w=1200&auto=format&fit=crop",
    gallery: [],
    popularityScore: 4.1,
    overview: "City of Joy — literature, art and incredible street food.",
    countryInfo: "India is a vast South Asian country with diverse terrain.",
    historicalSignificance: "Former capital of British India, boasting grand colonial architecture.",
    weatherInsights: "Tropical wet-and-dry climate. Very hot summers and heavy monsoons.",
    bestTimeToVisit: "October to March.",
    safetyTips: "Generally safe. Drink bottled water and be cautious with very spicy street food.",
    transportationDetails: "Yellow taxis, metro, buses, and the iconic tram system.",
    mustVisitPlaces: ["Victoria Memorial", "Howrah Bridge", "Dakshineswar Kali Temple", "Indian Museum"],
    topExperiences: ["Riding the heritage tram", "Eating at Park Street", "Durga Puja festival (in Autumn)"],
    famousFor: ["Sweets (Rosogolla)", "Literature", "Colonial Architecture", "Street Food"],
    hiddenGems: ["Kumartuli (idol makers' colony)", "College Street book market", "South Park Street Cemetery"],
    bestPhotoSpots: ["Prinsep Ghat at sunset", "Howrah Bridge", "Victoria Memorial grounds"],
    localFoodSpecialties: ["Kathi Roll", "Phuchka", "Macher Jhol", "Mishti Doi"],
    nightlife: ["Park Street pubs", "Someplace Else (live music)"],
    adventureActivities: ["Sundarbans mangrove tour (nearby)"],
    familyFriendly: ["Science City", "Alipore Zoo", "Eco Park"],
    tags: ["Culture", "Food", "History"],
    category: "Historical",
    budgetCategory: "Budget",
    adventureLevel: "Low",
    estimatedCosts: { hotel: 35, food: 15, transport: 5, attractions: 10, activities: 10, shopping: 20, dailyAverage: 95, category: "Budget" }
  }
];