/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as AiPlannerRouteImport } from './routes/ai-planner'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsNewRouteImport } from './routes/trips/new'
import { Route as TripsTripIdShareRouteImport } from './routes/trips/$tripId/share'
import { Route as TripsTripIdPackingRouteImport } from './routes/trips/$tripId/packing'
import { Route as TripsTripIdJournalRouteImport } from './routes/trips/$tripId/journal'
import { Route as TripsTripIdItineraryRouteImport } from './routes/trips/$tripId/itinerary'
import { Route as TripsTripIdBudgetRouteImport } from './routes/trips/$tripId/budget'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlannerRoute = AiPlannerRouteImport.update({
  id: '/ai-planner',
  path: '/ai-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdShareRoute = TripsTripIdShareRouteImport.update({
  id: '/trips/$tripId/share',
  path: '/trips/$tripId/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdPackingRoute = TripsTripIdPackingRouteImport.update({
  id: '/trips/$tripId/packing',
  path: '/trips/$tripId/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdJournalRoute = TripsTripIdJournalRouteImport.update({
  id: '/trips/$tripId/journal',
  path: '/trips/$tripId/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdItineraryRoute = TripsTripIdItineraryRouteImport.update({
  id: '/trips/$tripId/itinerary',
  path: '/trips/$tripId/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdBudgetRoute = TripsTripIdBudgetRouteImport.update({
  id: '/trips/$tripId/budget',
  path: '/trips/$tripId/budget',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/ai-planner': typeof AiPlannerRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/places': typeof PlacesRoute
  '/profile': typeof ProfileRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/budget': typeof TripsTripIdBudgetRoute
  '/trips/$tripId/itinerary': typeof TripsTripIdItineraryRoute
  '/trips/$tripId/journal': typeof TripsTripIdJournalRoute
  '/trips/$tripId/packing': typeof TripsTripIdPackingRoute
  '/trips/$tripId/share': typeof TripsTripIdShareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/ai-planner': typeof AiPlannerRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/places': typeof PlacesRoute
  '/profile': typeof ProfileRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/budget': typeof TripsTripIdBudgetRoute
  '/trips/$tripId/itinerary': typeof TripsTripIdItineraryRoute
  '/trips/$tripId/journal': typeof TripsTripIdJournalRoute
  '/trips/$tripId/packing': typeof TripsTripIdPackingRoute
  '/trips/$tripId/share': typeof TripsTripIdShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/ai-planner': typeof AiPlannerRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/places': typeof PlacesRoute
  '/profile': typeof ProfileRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/budget': typeof TripsTripIdBudgetRoute
  '/trips/$tripId/itinerary': typeof TripsTripIdItineraryRoute
  '/trips/$tripId/journal': typeof TripsTripIdJournalRoute
  '/trips/$tripId/packing': typeof TripsTripIdPackingRoute
  '/trips/$tripId/share': typeof TripsTripIdShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/ai-planner'
    | '/cities'
    | '/dashboard'
    | '/login'
    | '/places'
    | '/profile'
    | '/trips/new'
    | '/trips/$tripId/budget'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId/journal'
    | '/trips/$tripId/packing'
    | '/trips/$tripId/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/admin'
    | '/ai-planner'
    | '/cities'
    | '/dashboard'
    | '/login'
    | '/places'
    | '/profile'
    | '/trips/new'
    | '/trips/$tripId/budget'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId/journal'
    | '/trips/$tripId/packing'
    | '/trips/$tripId/share'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/ai-planner'
    | '/cities'
    | '/dashboard'
    | '/login'
    | '/places'
    | '/profile'
    | '/trips/new'
    | '/trips/$tripId/budget'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId/journal'
    | '/trips/$tripId/packing'
    | '/trips/$tripId/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRoute
  AiPlannerRoute: typeof AiPlannerRoute
  CitiesRoute: typeof CitiesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PlacesRoute: typeof PlacesRoute
  ProfileRoute: typeof ProfileRoute
  TripsNewRoute: typeof TripsNewRoute
  TripsTripIdBudgetRoute: typeof TripsTripIdBudgetRoute
  TripsTripIdItineraryRoute: typeof TripsTripIdItineraryRoute
  TripsTripIdJournalRoute: typeof TripsTripIdJournalRoute
  TripsTripIdPackingRoute: typeof TripsTripIdPackingRoute
  TripsTripIdShareRoute: typeof TripsTripIdShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-planner': {
      id: '/ai-planner'
      path: '/ai-planner'
      fullPath: '/ai-planner'
      preLoaderRoute: typeof AiPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/share': {
      id: '/trips/$tripId/share'
      path: '/trips/$tripId/share'
      fullPath: '/trips/$tripId/share'
      preLoaderRoute: typeof TripsTripIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/packing': {
      id: '/trips/$tripId/packing'
      path: '/trips/$tripId/packing'
      fullPath: '/trips/$tripId/packing'
      preLoaderRoute: typeof TripsTripIdPackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/journal': {
      id: '/trips/$tripId/journal'
      path: '/trips/$tripId/journal'
      fullPath: '/trips/$tripId/journal'
      preLoaderRoute: typeof TripsTripIdJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/itinerary': {
      id: '/trips/$tripId/itinerary'
      path: '/trips/$tripId/itinerary'
      fullPath: '/trips/$tripId/itinerary'
      preLoaderRoute: typeof TripsTripIdItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/budget': {
      id: '/trips/$tripId/budget'
      path: '/trips/$tripId/budget'
      fullPath: '/trips/$tripId/budget'
      preLoaderRoute: typeof TripsTripIdBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRoute,
  AiPlannerRoute: AiPlannerRoute,
  CitiesRoute: CitiesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PlacesRoute: PlacesRoute,
  ProfileRoute: ProfileRoute,
  TripsNewRoute: TripsNewRoute,
  TripsTripIdBudgetRoute: TripsTripIdBudgetRoute,
  TripsTripIdItineraryRoute: TripsTripIdItineraryRoute,
  TripsTripIdJournalRoute: TripsTripIdJournalRoute,
  TripsTripIdPackingRoute: TripsTripIdPackingRoute,
  TripsTripIdShareRoute: TripsTripIdShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
